[tox]
minversion = 1.8
basepython = python3
envlist = py3
skipsdist = true

[testenv]
passenv = *
setenv =
    ANSIBLE_COLLECTIONS_PATH = {envdir}/collections
deps =
    -r tox-requirements.txt
    ansible-core>=2.15,<2.16
commands_pre =
    ansible-galaxy collection install containers.podman -p {envdir}/collections
commands =
    {posargs:molecule test -s lightweight --destroy always}
