---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    clickhouse_host: "127.0.0.1"
    clickhouse_user: "user"
    clickhouse_password: "password"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Apply role under test
      ansible.builtin.include_role:
        name: netology.vector
