input {
    beats {
        port => 5044
    }
    tcp{
        port => 5046
        codec => json
    }
}

output {
    elasticsearch {
        hosts => ["http://es-hot:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
    }
}
