---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 
  - src: git@github.com:wacko-io/ansible-vector-role.git
    scm: git
    version: "0.1.0"
    name: vector-role
  - src: git@github.com:wacko-io/ansible-lighthouse.git
    scm: git
    version: "0.1.0"
    name: lighthouse
  - src: git@github.com:wacko-io/ansible-nginx.git
    scm: git
    version: "0.1.0"
    name: nginx