apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: busybox
          image: busybox
          command:
            - sh
            - -c
            - |
              until nslookup nginx-service.default.svc.cluster.local; do
                echo "svc not ready"
                sleep 2
              done
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80