---
# vars file for vector-role
vector_arch: "x86_64-unknown-linux-musl"
vector_archive: "vector-{{ vector_version }}-{{ vector_arch }}.tar.gz"
vector_url: "https://packages.timber.io/vector/{{ vector_version }}/{{ vector_archive }}"
vector_release_dir: "/opt/vector-{{ vector_version }}-{{ vector_arch }}"
