---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 93.77.191.99
vector:
  hosts:
    vector-01:
      ansible_host: 89.169.155.110
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 111.88.249.179