---
- name: NGINX | Install epel-release
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: NGINX | Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: Start nginx
