---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-sc
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/data-sc
  storageClassName: local-storage
---
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc-sc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-sc
  template:
    metadata:
      name: data-exchange-sc
      labels:
        app: data-exchange-sc
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["while true; do echo $(date) >> /data/file3.txt; sleep 5; done"]
          volumeMounts:
          - name: storage
            mountPath: /data
        - name: multitool
          image: wbitt/network-multitool
          command: ["/bin/sh", "-c"]
          args: ["tail -F /data/file3.txt"]
          volumeMounts:
              - name: storage
                mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: data-pvc-sc